---
- name: Run Backend
  docker_container:
    name: back_hw
    image: oxynep/tp-devops-cpe:back
    state: started
    exposed_ports:
      - 8080
    networks:
      - name: backend
      - name: frontend