name: Test Backend
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: master
  pull_request:
# nécessaire pour git
env:
  GITHUB_TOKEN: $(secrets.GITHUB_TOKEN)
jobs:

  test-backend:
    on:
      push:
        paths:
          - 'back/**'
    runs-on: ubuntu-18.04
    steps:
      #checkout your github code using actions/checkout@v2.3.3
      - uses: actions/checkout@v2.3.3
      #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      #finally build your app with the latest command
      - name: Build and test with Maven
      # run maven et l'analyse sonar
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=Oxynep_DevOps_TP1 -Dsonar.organization=oxynep -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{secrets.SONAR_TOKEN_DEVOPS}} --file ./back/simple-api-main