name: Build And Push Front Main
on:
  branches:
    - main
  push:
    paths:
      - 'devops-front-main/**'
jobs:
  build-and-push-docker-image-front-main:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:        
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_USR }} -p ${{secrets.DOCKER_HUB_PWD }}
      - name: Build image and push front
        uses: docker/build-push-action@v2
        with:
        # relative path to the place where source code with Dockerfile is located
          context: ./devops-front-main
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_HUB_USR}}/tp-devops-cpe:front_main
          push: ${{ github.ref == 'refs/heads/master'}}
