name: Build And Push Backend
on:
  workflow_run:
    workflows: ["Test Backend"]
    types: [completed]
    push:
      paths:
        - 'back/**'
      branches:
        - master
jobs:
  build-and-push-docker-image-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:        
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_USR }} -p ${{secrets.DOCKER_HUB_PWD }}
        
      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
        # relative path to the place where source code with Dockerfile is located
          context: ./back
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_HUB_USR}}/tp-devops-cpe:back
          push: ${{ github.ref == 'refs/heads/master'}}